name: my_fist_workflow

on: push

jobs:
    build-jobs-1:
        runs-on: ubuntu-latest
        steps: 
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay cmd
          run: cowsay -f dragon "run for cover" >> dragon.txt
        - name: Sleep for 30 sec
          run: sleep 30


    test-jobs-2:
        needs: [build-jobs-1]
        runs-on: ubuntu-latest
        steps: 
        - name: Sleep for 10 sec
          run: sleep 10
        - name: Test if file exist
          run: ls -ltrha

          
    deploy-jobs-3:
        needs: [test-jobs-2]
        runs-on: ubuntu-latest
        steps: 
        - name: create a file
          run: touch bob.txt
        - name: list the file
          run: ls  -ltrha
        - name: Deploy
          run: echo Deploying ...

          