name: my_fist_workflow

on: push

jobs:
    first-jobs:
        runs-on: ubuntu-latest
        steps: 
        - name: check-out
          uses: actions/checkout@v5

        - name: list all the file
          run: ls -ltrh
        - name: provide the enought pemission
          run: chmod +x .github/workflows/bash.sh


        - name: Executing shell script
          run:  ./.github/workflows/bash.sh
          