name: my_fist_workflow

on: push 

jobs:
    build-jobs-1:
        runs-on: ubuntu-latest
        steps: 
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        - name: Execute cowsay cmd
          run: cowsay -f dragon "run for cover" >> dragon.txt
        - name: upload the dragon file
          uses: actions/upload-artifact@v4
          with:
           name: my-artifact
           path: dragon.txt


    test-jobs-2:
        needs: [build-jobs-1]
        runs-on: ubuntu-latest
        steps: 
        - name: upload the dragon file
          uses: actions/download-artifact@v4
          with:
            name: my-artifact
        - name: Test if file exist
          run: ls -ltrha

          
    deploy-jobs-3:
        needs: [test-jobs-2]
        runs-on: ubuntu-latest
        steps: 
        - name: upload the dragon file
          uses: actions/download-artifact@v4
          with:
           name: my-artifact
        - name: read the file
          run: |
           cat dragon.txt
           ls -ltrh
        - name: Deploy
          run: echo Deploying ...

          