name: my_fist_workflow

on: push

jobs:
    first-jobs:
        runs-on: ubuntu-latest
        steps: 
        - name: check-out
          uses: actions/checkout@v5
        - name: List the all file and welcome message
          run: |
           ls -ltrh
           echo "Hello! alice how are you doing"

        - name: Generate Ascci Artwork
          run: cowsay -f dragon "Run for art work, and save it to dragaon.txt" >> dragon.txt

          