name: my_fist_workflow

on: push

jobs:
    first-jobs:
        runs-on: ubuntu-latest
        steps: 
        - name: check-out
          uses: actions/checkout@v5

        - name: list all the file
          run: ls -ltrh


        - name: Executing shell script
          run: |
           chmod +x .github/workflows/bash.sh
           ./.github/workflows/bash.sh
          